In [8]:
import pandas as pd
import numpy as np

In [128]:
df = pd.read_csv('D:/utp/IA/data_rrss.csv', sep=';',index_col=4,usecols=['edad','raza dominante','emocion','genero','id'])
df

                                      edad   raza dominante  emocion genero
id
0a85cef5-12c3-4b18-a582-9b08e9965e73    28  latino hispanic  neutral    Man
0a85cef5-12c3-4b18-a582-9b08e9965e73    28  latino hispanic  neutral    Man
0a85cef5-12c3-4b18-a582-9b08e9965e73    27  latino hispanic  neutral    Man
0a85cef5-12c3-4b18-a582-9b08e9965e73    28  latino hispanic  neutral    Man
0a85cef5-12c3-4b18-a582-9b08e9965e73    28  latino hispanic  neutral    Man
...                                    ...              ...      ...    ...
72eda2db-c4fc-4561-a5e7-1076cce47af4    29   middle eastern    happy    Man
72eda2db-c4fc-4561-a5e7-1076cce47af4    29   middle eastern    happy    Man
72eda2db-c4fc-4561-a5e7-1076cce47af4    28   middle eastern    happy    Man
72eda2db-c4fc-4561-a5e7-1076cce47af4    28   middle eastern    happy    Man
72eda2db-c4fc-4561-a5e7-1076cce47af4    29   middle eastern    happy    Man

[283 rows x 4 columns]

In [129]:
data_group = df.groupby(['id','edad','raza dominante','emocion','genero']).size().reset_index().rename(columns={0:'cantidad'})
data_group

,id,edad,raza dominante,emocion,genero,cantidad
0,0a85cef5-12c3-4b18-a582-9b08e9965e73,26,latino hispanic,angry,Man,2
1,0a85cef5-12c3-4b18-a582-9b08e9965e73,26,latino hispanic,neutral,Man,32
2,0a85cef5-12c3-4b18-a582-9b08e9965e73,27,latino hispanic,neutral,Man,80
3,0a85cef5-12c3-4b18-a582-9b08e9965e73,27,latino hispanic,sad,Man,15
4,0a85cef5-12c3-4b18-a582-9b08e9965e73,28,latino hispanic,angry,Man,2
5,0a85cef5-12c3-4b18-a582-9b08e9965e73,28,latino hispanic,neutral,Man,24
6,0a85cef5-12c3-4b18-a582-9b08e9965e73,28,latino hispanic,sad,Man,4
7,133325b4-bca5-4f74-bb91-685aa4389d11,27,latino hispanic,neutral,Man,2
8,72eda2db-c4fc-4561-a5e7-1076cce47af4,26,middle eastern,fear,Man,2
9,72eda2db-c4fc-4561-a5e7-1076cce47af4,26,middle eastern,happy,Man,5
10,72eda2db-c4fc-4561-a5e7-1076cce47af4,27,middle eastern,fear,Man,4
11,72eda2db-c4fc-4561-a5e7-1076cce47af4,27,middle eastern,happy,Man,13
12,72eda2db-c4fc-4561-a5e7-1076cce47af4,27,middle eastern,neutral,Man,4
13,72eda2db-c4fc-4561-a5e7-1076cce47af4,28,middle eastern,fear,Man,3
14,72eda2db-c4fc-4561-a5e7-1076cce47af4,28,middle eastern,happy,Man,54
15,72eda2db-c4fc-4561-a5e7-1076cce47af4,28,middle eastern,neutral,Man,4
16,72eda2db-c4fc-4561-a5e7-1076cce47af4,29,middle eastern,happy,Man,25
17,72eda2db-c4fc-4561-a5e7-1076cce47af4,29,middle eastern,neutral,Man,4
18,72eda2db-c4fc-4561-a5e7-1076cce47af4,30,middle eastern,happy,Man,2
19,72eda2db-c4fc-4561-a5e7-1076cce47af4,31,middle eastern,neutral,Man,2

In [130]:
dg = pd.DataFrame(data_group)
dg

,id,edad,raza dominante,emocion,genero,cantidad
0,0a85cef5-12c3-4b18-a582-9b08e9965e73,26,latino hispanic,angry,Man,2
1,0a85cef5-12c3-4b18-a582-9b08e9965e73,26,latino hispanic,neutral,Man,32
2,0a85cef5-12c3-4b18-a582-9b08e9965e73,27,latino hispanic,neutral,Man,80
3,0a85cef5-12c3-4b18-a582-9b08e9965e73,27,latino hispanic,sad,Man,15
4,0a85cef5-12c3-4b18-a582-9b08e9965e73,28,latino hispanic,angry,Man,2
5,0a85cef5-12c3-4b18-a582-9b08e9965e73,28,latino hispanic,neutral,Man,24
6,0a85cef5-12c3-4b18-a582-9b08e9965e73,28,latino hispanic,sad,Man,4
7,133325b4-bca5-4f74-bb91-685aa4389d11,27,latino hispanic,neutral,Man,2
8,72eda2db-c4fc-4561-a5e7-1076cce47af4,26,middle eastern,fear,Man,2
9,72eda2db-c4fc-4561-a5e7-1076cce47af4,26,middle eastern,happy,Man,5
10,72eda2db-c4fc-4561-a5e7-1076cce47af4,27,middle eastern,fear,Man,4
11,72eda2db-c4fc-4561-a5e7-1076cce47af4,27,middle eastern,happy,Man,13
12,72eda2db-c4fc-4561-a5e7-1076cce47af4,27,middle eastern,neutral,Man,4
13,72eda2db-c4fc-4561-a5e7-1076cce47af4,28,middle eastern,fear,Man,3
14,72eda2db-c4fc-4561-a5e7-1076cce47af4,28,middle eastern,happy,Man,54
15,72eda2db-c4fc-4561-a5e7-1076cce47af4,28,middle eastern,neutral,Man,4
16,72eda2db-c4fc-4561-a5e7-1076cce47af4,29,middle eastern,happy,Man,25
17,72eda2db-c4fc-4561-a5e7-1076cce47af4,29,middle eastern,neutral,Man,4
18,72eda2db-c4fc-4561-a5e7-1076cce47af4,30,middle eastern,happy,Man,2
19,72eda2db-c4fc-4561-a5e7-1076cce47af4,31,middle eastern,neutral,Man,2

In [131]:
data_procesada = dg.groupby(['id'])['cantidad'].max().reset_index()
data_procesada

                                     id  cantidad
0  0a85cef5-12c3-4b18-a582-9b08e9965e73        80
1  133325b4-bca5-4f74-bb91-685aa4389d11         2
2  72eda2db-c4fc-4561-a5e7-1076cce47af4        54

In [132]:
ls = []
for i, row in data_procesada.iterrows():
    al = d[(d['cantidad'] == int(row['cantidad'])) & (d['id'] == row['id'])]
    print(al.id.values[0])
    ls.append([al['id'].values[0],al['edad'].values[0],al['raza dominante'].values[0],al['emocion'].values[0],al['genero'].values[0]])
    
data_limpia =  pd.DataFrame(ls,columns=['id','edad','raza dominante','emocion','genero'])
data_limpia

0a85cef5-12c3-4b18-a582-9b08e9965e73
133325b4-bca5-4f74-bb91-685aa4389d11
72eda2db-c4fc-4561-a5e7-1076cce47af4

                                     id  edad   raza dominante  emocion genero
0  0a85cef5-12c3-4b18-a582-9b08e9965e73    27  latino hispanic  neutral    Man
1  133325b4-bca5-4f74-bb91-685aa4389d11    27  latino hispanic  neutral    Man
2  72eda2db-c4fc-4561-a5e7-1076cce47af4    28   middle eastern    happy    Man